name: Docs

on:
  push:
    branches: [ main ]
    paths:
      - "pyproject.toml"
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"

env:
  POETRY_VERSION: "1.3.2"

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    
    steps:
    # ---------------------------------------------
    # -----           gather repo             -----
    # ---------------------------------------------
    - uses: actions/checkout@v3

    # ---------------------------------------------
    # -----      setup and cache python       -----
    # ---------------------------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}

    - name: Install poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-in-project: true

    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}-

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: poetry install --all-extras

    #----------------------------------------------
    #  -----       build & deploy docs       -----
    #----------------------------------------------
    - name: Build and deploy documentation
      if: |
        github.repository == '0xPlaygrounds/subgrounds'
        && github.event_name == 'push'
        && github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        poetry run mudkip build --update-gh-pages --repository https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
